version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_service
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  auth-service:
    build: .
    container_name: auth-service-mysql
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=auth_user
      - DB_PASSWORD=password
      - DB_NAME=auth_service
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - mysql

volumes:
  mysql_data:
