services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - PORT=8081
      - ENV=development
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/auth_service.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRATION_HOURS=24
      - JWT_REFRESH_EXPIRATION_HOURS=168
    ports:
      - "8081:8081"
    volumes:
      - auth_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  auth_data: